// post-data.ts
export const postData = [
  {
    id: 1,
    title: 'The Art of Angular',
    content: 'Learn the ins and outs of Angular development in this comprehensive guide.',
    imageUrl: 'https://greymatterz.com/blogs/assets/images/blog/angular-framework-20220317114512-Z1AK8C.png',
    date: '2023-11-20',
    author: 'John Doe',
    category: 'Programming',
    tags: ['Angular', 'Web Development'],
  },
  {
    id: 2,
    title: 'Mastering React.js',
    content: 'Unlock the full potential of React.js with advanced techniques and best practices.',
    imageUrl: 'https://i1.wp.com/media.geeksforgeeks.org/wp-content/cdn-uploads/20200309202057/How-To-Learn-ReactJS-A-Complete-Guide-For-Beginners.jpg',
    date: '2023-11-21',
    author: 'Jane Smith',
    category: 'Programming',
    tags: ['React.js', 'Frontend'],
  },
  {
    id: 3,
    title: 'Introduction to Machine Learning',
    content: 'Explore the fundamentals of machine learning and its real-world applications.',
    imageUrl: 'https://science4data.com/wp-content/uploads/2018/11/4178c478-b73c-4437-a086-ad2c7583e70f.jpg',
    date: '2023-11-22',
    author: 'Alex Johnson',
    category: 'Machine Learning',
    tags: ['Machine Learning', 'Data Science'],
  },
  {
    id: 4,
    title: 'The World of JavaScript',
    content: 'Dive deep into the world of JavaScript and discover its versatility.',
    imageUrl: 'https://res.cloudinary.com/academind-gmbh/image/upload/c_fit,w_1600,h_900/v1/academind.com/content/tutorials/the-world-of-javascript/the-world-of-javascript',
    date: '2023-11-23',
    author: 'Emily Brown',
    category: 'Programming',
    tags: ['JavaScript', 'Web Development'],
  },
  {
    id: 5,
    title: 'Data Science for Beginners',
    content: 'Get started with data science and learn essential concepts for beginners.',
    imageUrl: 'https://i.ytimg.com/vi/pRJkERVL2qE/maxresdefault.jpg',
    date: '2023-11-24',
    author: 'Daniel Lee',
    category: 'Data Science',
    tags: ['Data Science', 'Statistics'],
  },
  {
    id: 6,
    title: 'Frontend Frameworks Comparison',
    content: 'Compare popular frontend frameworks to choose the right one for your project.',
    imageUrl: 'https://www.upsqode.com/wp-content/uploads/2022/08/10-Best-Frontend-Frameworks-1.png',
    date: '2023-11-25',
    author: 'Sarah Thompson',
    category: 'Web Development',
    tags: ['React.js', 'Angular', 'Vue.js'],
  },
  {
    id: 7,
    title: 'Getting Started with Python',
    content: 'Begin your journey into the world of Python programming with this beginner-friendly guide.',
    imageUrl: 'https://ysc-nepal.org/wp-content/uploads/2020/11/python.jpg',
    date: '2023-11-26',
    author: 'Michael Wilson',
    category: 'Programming',
    tags: ['Python', 'Programming'],
  },
  {
    id: 8,
    title: 'Responsive Web Design Techniques',
    content: 'Learn essential techniques for creating responsive and mobile-friendly websites.',
    imageUrl: 'https://www.helixdigital.com.au/wp-content/uploads/2018/10/responsive-website-design.jpg',
    date: '2023-11-27',
    author: 'Emma Davis',
    category: 'Web Development',
    tags: ['Responsive Design', 'CSS'],
  },
  {
    id: 9,
    title: 'Exploring Backend Technologies',
    content: 'Discover various backend technologies and their use cases in modern web development.',
    imageUrl: 'https://ddi-dev.com/uploads/backend-is.png',
    date: '2023-11-28',
    author: 'Chris Miller',
    category: 'Web Development',
    tags: ['Node.js', 'Django', 'Express.js'],
  },
  {
    id: 10,
    title: 'Understanding APIs',
    content: 'Gain a deep understanding of APIs and their role in connecting different software applications.',
    imageUrl: 'https://lunaconnect.io/wp-content/uploads/2022/02/Featured-Image_Why-API-Integration-1-1536x1229.jpg',
    date: '2023-11-29',
    author: 'Olivia Harris',
    category: 'Web Development',
    tags: ['APIs', 'Web Services'],
  },
  {
    id: 11,
    title: 'Artificial Intelligence in Healthcare',
    content: 'Explore the applications of artificial intelligence in the healthcare industry.',
    imageUrl: 'https://th.bing.com/th/id/OIP.AKMQfhf3yTqEvkDit4PMOwHaEK?rs=1&pid=ImgDetMain',
    date: '2023-11-30',
    author: 'William Turner',
    category: 'Artificial Intelligence',
    tags: ['AI', 'Healthcare'],
  },
  {
    id: 12,
    title: 'The Future of Blockchain',
    content: 'Learn about the potential and future developments of blockchain technology.',
    imageUrl: 'https://www.techulator.com/attachments/resources/17642-1-Blockchain-development-in-india.jpg',
    date: '2023-12-01',
    author: 'Sophia White',
    category: 'Blockchain',
    tags: ['Blockchain', 'Cryptocurrency'],
  },
  {
    id: 13,
    title: 'Mobile App Development Trends',
    content: 'Stay updated on the latest trends and advancements in mobile app development.',
    imageUrl: 'https://catalystforbusiness.com/wp-content/uploads/2018/11/mobile-app-development-trends.jpg',
    date: '2023-12-02',
    author: 'Jason Reed',
    category: 'Mobile Development',
    tags: ['Mobile Apps', 'iOS', 'Android'],
  },
  {
    id: 14,
    title: 'Cybersecurity Best Practices',
    content: 'Learn essential cybersecurity practices to protect your digital assets.',
    imageUrl: 'https://th.bing.com/th/id/OIP.XcEtqdrPJgE5zI7Pl6ls_wHaEM?rs=1&pid=ImgDetMain',
    date: '2023-12-03',
    author: 'Eva Martinez',
    category: 'Cybersecurity',
    tags: ['Cybersecurity', 'Online Security'],
  },
  {
    id: 15,
    title: 'Cloud Computing Explained',
    content: 'Understand the concepts and benefits of cloud computing in modern IT infrastructure.',
    imageUrl: 'https://www.marketwatchmedia.com/wp-content/uploads/2022/08/Cloud-Computing-2.jpg',
    date: '2023-12-04',
    author: 'Ryan Clark',
    category: 'Cloud Computing',
    tags: ['Cloud', 'AWS', 'Azure'],
  },
  {
    id: 16,
    title: 'E-commerce Website Development',
    content: 'Learn the key aspects of developing a successful e-commerce website.',
    imageUrl: 'https://www.venturessky.com/wp-content/uploads/2021/09/e-commerce-2.jpg',
    date: '2023-12-05',
    author: 'Ava Turner',
    category: 'Web Development',
    tags: ['E-commerce', 'Online Shopping'],
  },
  {
    id: 17,
    title: 'Introduction to UX/UI Design',
    content: 'Get started with user experience (UX) and user interface (UI) design principles.',
    imageUrl: 'https://th.bing.com/th/id/OIP.Gv3TsvcQcHL_qAcp0lO2UQAAAA?rs=1&pid=ImgDetMain',
    date: '2023-12-06',
    author: 'Lucas Garcia',
    category: 'Design',
    tags: ['UX/UI', 'Design Principles'],
  },
  {
    id: 18,
    title: 'DevOps Culture and Practices',
    content: 'Explore the culture and practices of DevOps in modern software development.',
    imageUrl: 'https://www.bdccglobal.com/wp-content/uploads/2019/11/devops-best-practices-min-1024x512.png',
    date: '2023-12-07',
    author: 'Isabella Adams',
    category: 'DevOps',
    tags: ['DevOps', 'Continuous Integration'],
  },
  {
    id: 19,
    title: 'Game Development Basics',
    content: 'Learn the basics of game development and start creating your own games.',
    imageUrl: 'https://whatshouldiplaytoday.files.wordpress.com/2016/06/a8-design-bowring-41.jpg?w=768',
    date: '2023-12-08',
    author: 'Nathan Roberts',
    category: 'Game Development',
    tags: ['Game Development', 'Unity'],
  },
  {
    id: 20,
    title: 'Big Data Analytics Fundamentals',
    content: 'Understand the fundamentals of big data analytics and its impact on business.',
    imageUrl: 'https://th.bing.com/th/id/OIP.R4nVjnLKT3pddFfUlt8ejQHaFL?rs=1&pid=ImgDetMain',
    date: '2023-12-09',
    author: 'Sophie Turner',
    category: 'Big Data',
    tags: ['Big Data', 'Analytics'],
  },
];
